### ISSUE TITLE
How should i get correspond tensorboard graph ? 

### ISSUE THREAD

**Issue by yuanzhanghu** [noootown/Forex-DQN#1]
Just like what you presented.

**Comment by noootown** [comment]
Hi can you tell me more about your question?
Feel free to write in chinese

**Comment by yuanzhanghu** [comment]
谢谢！我怎么才能通过程序运行， 得到你贴出来的那些图？

**Comment by yuanzhanghu** [comment]
Also i didn't see any DQN related code in your RLBrain file.   Could you introduce a bit about your algorithm ?  Thanks!

**Comment by noootown** [comment]
You should be able to found some information about DQN on the internet. I don't think my code is too complicate too understand and please remember, Google is your best friend.

**Comment by noootown** [comment]
About the first question, please run` python3 py/train.py -h ` and you'll see help, thanks

**Comment by yuanzhanghu** [comment]
From your RLBrain file, i didn't see you were using CNN layer.  That's why i said i didn't see DQN code.  maybe i missed something in your code ?   
For first question,  i got this from 'python3 train/index.py -h':
yhu@yhu-Aspire-M3920:~/workspace/deeplearning/Forex-DQN$ python3 train/index.py -h                              │
python3 train/index.py                                                                                          │
-d <dir>: assign the output directory to data/<dir>                                                             │
-h --help: help                                                                                                 │
-l <num>: load ckpt file from <dir>/history/<num>                                                               │
-o: command line output result                                                                                  │
-t: testing mode, default: training mode          

Which one can i use to generate tensorboard graph ?   Sorry maybe i have too many questions ?

**Comment by yuanzhanghu** [comment]
Sorry, i am still new to AI area,   just figured out how to use tensorboard.    Just ignore my first question please.   Still trying to understand your algo...    :+1:

**Comment by noootown** [comment]
Sorry, I was too busy and didn't look into your first question, to generate tensorboard, you must run `tensorboard --logdir=XXX`, please checkout tensorboard API.
And as for DQN, it is not a CNN algorithm, I think you should find more informations about DQN and understand it.

If you are a beginner and trying to look into AI or deep learning, I think my project is not a good starter kit since it contains advance algorithm like DQN. You can checkout 莫煩's video.

加油 :)
