### ISSUE TITLE
how it goes in real forex market?

### ISSUE THREAD

**Issue by imkow** [noootown/Forex-DQN#2]
did you test it in real market or any accurate backtesting result?

thx.

**Comment by noootown** [comment]
Yes it has been deployed to real market, and is proved to work. However for certain reasons, I closed it. Before I found a way to avoid those problems, I won't open it.

**Comment by imkow** [comment]
@noootown could you be more specific about what were those problems? thx

**Comment by noootown** [comment]
The biggest problem is risk. How much risk can your model take?
If your model is proved to work in the past, how long will it work in the future?

There are many problems to solve and each problem may cause a big lost.

**Comment by imkow** [comment]
@noootown Thx. Do you mean most risks caused by position sizing/money management?

**Comment by noootown** [comment]
Yeah, but I'm not an expert in finance, so I can't comment more about this.
But the main idea is we can actually predict future, so we must take risk into account.

**Comment by imkow** [comment]
@noootown that's right, I have been doing forex for years. Of course, nobody can predict future. Risks must always be watched. 

So, is this project doing forex by prediction?

**Comment by noootown** [comment]
Yes, the main algorithm DQN in this project is used to predict the future.

**Comment by imkow** [comment]
@noootown as a matter of fact, if you really wanted to predict, you may predict using economic/political  events/news and their relationship with forex. Of course, that would be another topic involving NLP, etc. 

Thx.

**Comment by noootown** [comment]
Oh, I think that's the scope of fundamental analysis (I'm not sure if I translate it right), and I'm only focusing on the short term technical analysis, that is only by candlesticks.
