### ISSUE TITLE
config Package Problem

### ISSUE THREAD

**Issue by mahdifarshid** [noootown/Forex-DQN#4]
hi i installed config packge but getConfig not works

this line of code not works for me
from config import getConfig

  File "train/index.py", line 11, in <module>
    from config import getConfig
ImportError: cannot import name 'getConfig' from 'config' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/config.py)

**Comment by Bim-n-Biwl** [comment]
did you find a solution?  I am wondering about this too..
